# vim ft=yaml
# travis-ci.org definition for game-of-life build
#

language: c
env:
    - PYTHON=python PYSUF='' PYVER=2.7
    - PYTHON=python3 PYSUF='3' PYVER=3.2
install:
    - sudo apt-get update  # needed for python3-numpy
    - sudo apt-get install $PYTHON-dev
    - sudo apt-get install $PYTHON-numpy
    - sudo apt-get install $PYTHON-setuptools
    - sudo apt-get install $PYTHON-nose
    - sudo easy_install$PYSUF pip
    - if [[ $PYVER == '2.7' ]]; then sudo apt-get install $PYTHON-matplotlib; fi
    - if [[ $PYVER == '3.2' ]]; then sudo pip3 install matplotlib; fi

script:
    # Change into an innocuous directory and find tests from installation
    - mkdir $HOME/.matplotlib
    - "echo 'backend : Agg' > $HOME/.matplotlib/matplotlibrc"
    - "echo 'backend.qt4 : PyQt4' >> $HOME/.matplotlib/matplotlibrc"
    - "cd game-of-life"
    - if [[ $PYVER == '2.7' ]]; then nosetests-2.7; fi
    - if [[ $PYVER == '3.2' ]]; then nosetests-3.2; fi